//ASCII (American Standard Code for Information Interchange)
// It gave all computers a common language by converting characters into numbers

println("                      /\\");
println("                     /  \\");
println("                    /    \\");
println("                   /      \\");
println("                  /        \\");
println("                 /          \\");
println("                /            \\");
println("               |\\            /|");
println("               | \\          / |");
println("               |  \\        /  |");
println("               |   \\      /   |");
println("               |    \\    /    |");
println("               |     \\  /     |");
println("               |      \\/      |");
println("               |      }       |");
println("               |      {       |");
println("               |      }       |");
println("               |      {       |");
println("               |      }       |");
println("               |      {       |");
println("               |      }       |");
println("               |      {       |");
println("               |      }       |");
println("               |      {       |");
println("               |      }       |");
println("               |      {       |");
println("               |      }       |");
println("               |      {       |");
println("               |      }       |");
println("               |      {       |");
println("               |      }       |");
println("               |      {       |");
println("               |      }       |");
println("               |      {       |");
println("               |      }       |");
println("               |      {       |");
println("               |      }       |");
println("               |      {       |");
println(" ___________--------------------_____________");
println(" \\          \\                  /            /");
println("  \\________________________________________/");
println("                  \\  \\_/  /                   ");
println("                   \\_____/                   ");
println("                    |   |                   ");
println("                    |~~~|                   ");
println("                    |   |                   ");
println("                    |~~~|                   ");
println("                    |   |                   ");
println("                    |~~~|                   ");
println("                    |   |                   ");
println("                    |~~~|                   ");
println("                    |   |                   ");
println("                 __-------__");
println("                 \\_________/");
